name: Build proyecto
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        dotnetversion: ['5.0.x']
        nodeversion: ['16.x']
    steps:
      - uses: actions/checkout@v3
      
      - name: Set .net
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{matrix.dotnetversion}}

      - name: restaurar dependencias
        working-directory: ./Codigo/Backend/ArenaGestor/
        run: dotnet restore

      - name: build aplicacion
        working-directory: ./Codigo/Backend/ArenaGestor/ArenaGestor.API
        run: dotnet build --configuration Realese --no-restore 
